version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0  # Монтируем серийный порт Arduino в контейнер
    environment:
      - SERIAL_PORT=/dev/ttyUSB0
      - DB_USER=rackot
      - DB_PASSWORD=arduinologdb
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=arduinologdb
    depends_on:
      - db

  db:
    image: postgres:15.6
    restart: always
    environment:
      POSTGRES_USER: rackot
      POSTGRES_PASSWORD: arduinologdb
      POSTGRES_DB: arduinologdb
